### ISSUE TITLE
Hidden navbar does not show when hovering over empty space in tab bar

### ISSUE THREAD

**Issue by Faleij** [Faleij/Australis-Slimmr#1]
"If I only have one tab open, for instance, I can't just mouse over anywhere in the tab bar, I have to go all the way over to the left, even if what I'm wanting to do in the navigation bar is on the far right - meaning I have to keep the cursor over the newly thin nav bar corridor while I carefully move it back to the right.
I hope it's considered a bug in the author's eyes and not acceptable behavior." - Caspy7 November 30, 2013 at 11:39 pm @ http://www.ghacks.net/2013/11/30/australis-slimmr-slims-new-firefox-interface/

Response:
This is a bug, currently I do not know a good way of solving this.
Why this bug exist; I do listen for "hover" events with CSS on the "#navigator-toolbox" but that empty space next to the tab is just not responding to "hover" events in CSS.
I will do my best to try and find a good solution to this but I will take some time as I will be away for about one month starting tomorrow with only a tablet - so I can only do research and write down theories on how to possibly fix this but won't be able to test anything before the start of January, sorry.

**Comment by Faleij** [comment]
Update: Still unable to solve this.

**Comment by Keith94** [comment]
May be a long shot but there's another add-on that auto-hides the nav bar and doesn't display the issue described here, maybe you can adopt its techniques or something.
https://addons.mozilla.org/addon/lesschrome-modified/

**Comment by Faleij** [comment]
Thank you for your input on the matter but, after some extensive tests I can confirm that that add-on suffers from the same problem but it is less pronounce as it have some measures for keeping the bar visible when the mouse is above the browser window. However, if you start with it hidden and move the mouse down onto the empty space in tabsbar nothing will happen - as with my add-on. I have had a look at the source of that addon and there's nothing there that could help.

**Comment by Faleij** [comment]
Now the navbar is shown when the cursor leaves the content area thus partially solving the issue but it raises another visual issue; whenever your mouse leaves the browser - the navbar is visible. Please try it and kindly provide feedback.

**Comment by Faleij** [comment]
Closed with partial fix, good enough for release.
