### ISSUE TITLE
Hide locationbar issues

### ISSUE THREAD

**Issue by valentinritz** [Faleij/Australis-Slimmr#4]
Hi,

First of all, thanks for this nice addon!

Here are my issues : this addon disables the "Select LocationBar" hotkey ( Ctrl + L ).

Also, when I open a new tab, Firefox use to select the locationbar. This is also not the case when the option "automatically hide navigation bar" is enabled.

**Comment by Faleij** [comment]
Both issues are now fixed, just need to add the hotkey as an option as some may not want it. Releasing a new version some time soon. Beta test version should be available on github repo really soon - test it and report back.

**Comment by Faleij** [comment]
For testing: https://github.com/Faleij/Australis-Slimmr/blob/1ec2e00aa55e93741cb3f497474e4ec35f8a2410/australis-slimmr.xpi

**Comment by valentinritz** [comment]
Wow, this was quick ;) Thanks a lot for this :)

I've tested it and now when I open a new tab or press on Ctrl+L, the location bar is focused, which is great!
One little improvement could be to select the whole locationbar instead of just focusing the bar.

EDIT : Weird... Now it does select the whole url. I suppose this is fixed then :)

**Comment by Faleij** [comment]
"Faleij referenced this issue from a commit 42 minutes ago
        Issue #4 - Less visual issues, fix for Input boxes producing content-… …    20a49c9"
Wrong issue reference in commit.
