### ISSUE TITLE
Delay when using ctrl + L to focus location bar

### ISSUE THREAD

**Issue by tivac** [Faleij/Australis-Slimmr#8]
I'm using Australis Slimmr w/ the location bar visible and there's a noticeable, almost-a-second-feeling delay when hitting ctrl-l before the location bar is selected. It's slow enough that if I hit ctrl-l & then start immediately typing I end up searching in the current page.

If I'm not hiding the location bar I'd like it to not override ctrl-l so I can have my instant location bar selection back, please.

**Comment by Faleij** [comment]
This is actually already "fixed" but just not released on addons.Mozilla yet.
There is need for a small delay due to transition effects, it was way too large before but I have gotten it down to 200ms, I will try and get it lower.

**Comment by tivac** [comment]
Does it need to be there at all if I don't hide the location bar? I totally get why it makes sense to have in the case where the location bar needs to transition in to be visible.

**Comment by Faleij** [comment]
No it should not, I will try and remove the delay altogether when the location bar is always visible.

**Comment by tivac** [comment]
:+1: thanks!
